views:
  v1/pods:
    sortColumn: NAMESPACE:asc
    columns:
      - 'PF|H'
      - NAMESPACE
      - NAME
      - READY
      - STATUS
      - 'RESTARTS|R'
      - 'CPU|R'
      - 'MEM|R'
      - '%CPU/R|R'
      - '%CPU/L|R'
      - '%MEM/R|R'
      - '%MEM/L|R'
      - 'VERSION:.spec.containers[0].image|split(":")|.[-1]'
      - 'QOS:.status.qosClass|W'
      - 'SA:.spec.serviceAccountName|W'
      - 'NODE|W'
      - 'IP|W'
      - AGE

  apps/v1/deployments:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - READY
      - UP-TO-DATE
      - AVAILABLE
      - 'VERSION:.spec.template.spec.containers[0].image|split(":")|.[-1]'
      - 'STRATEGY:.spec.strategy.type|W'
      - AGE

  apps/v1/statefulsets:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - READY
      - 'VERSION:.spec.template.spec.containers[0].image|split(":")|.[-1]'
      - 'SERVICE:.spec.serviceName|W'
      - AGE

  apps/v1/daemonsets:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - DESIRED
      - CURRENT
      - READY
      - UP-TO-DATE
      - AVAILABLE
      - 'VERSION:.spec.template.spec.containers[0].image|split(":")|.[-1]'
      - 'NODE-SELECTOR|W'
      - AGE

  apps/v1/replicasets:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - DESIRED
      - CURRENT
      - READY
      - 'VERSION:.spec.template.spec.containers[0].image|split(":")|.[-1]'
      - AGE

  batch/v1/jobs:
    sortColumn: AGE:desc
    columns:
      - NAMESPACE
      - NAME
      - COMPLETIONS
      - DURATION
      - 'VERSION:.spec.template.spec.containers[0].image|split(":")|.[-1]'
      - AGE

  batch/v1/cronjobs:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - SCHEDULE
      - SUSPEND
      - ACTIVE
      - LAST-SCHEDULE
      - 'VERSION:.spec.jobTemplate.spec.template.spec.containers[0].image|split(":")|.[-1]'
      - AGE

  v1/services:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - TYPE
      - CLUSTER-IP
      - EXTERNAL-IP
      - PORTS
      - 'SELECTOR|S'
      - AGE

  v1/endpoints:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - ENDPOINTS
      - AGE

  networking.k8s.io/v1/ingresses:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - CLASS
      - HOSTS
      - ADDRESS
      - PORTS
      - AGE

  v1/persistentvolumeclaims:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - STATUS
      - VOLUME
      - CAPACITY
      - STORAGECLASS
      - AGE

  v1/persistentvolumes:
    sortColumn: AGE:desc
    columns:
      - NAME
      - CAPACITY
      - ACCESSMODES
      - RECLAIMPOLICY
      - STATUS
      - CLAIM
      - STORAGECLASS
      - AGE

  v1/configmaps:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - DATA
      - AGE

  v1/secrets:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - TYPE
      - DATA
      - AGE

  autoscaling/v2/horizontalpodautoscalers:
    sortColumn: NAMESPACE:asc
    columns:
      - NAMESPACE
      - NAME
      - REFERENCE
      - TARGETS
      - MINPODS
      - MAXPODS
      - REPLICAS
      - AGE

  v1/nodes:
    sortColumn: NAME:asc
    columns:
      - NAME
      - STATUS
      - ROLE
      - 'INSTANCE-TYPE:.metadata.labels.node\.kubernetes\.io/instance-type'
      - 'ZONE:.metadata.labels.topology\.kubernetes\.io/zone'
      - 'ARCH:.status.nodeInfo.architecture'
      - 'KERNEL:.status.nodeInfo.kernelVersion|W'
      - VERSION
      - 'CPU/A|R'
      - '%CPU/A|R'
      - 'MEM/A|R'
      - '%MEM/A|R'
      - 'POD/A|R'
      - 'TAINTS|W'
      - AGE
